version: 0.2

env:
  parameter-store:
    ECRID: "/Build/ECRID"
  variables:
    AWS_DEFAULT_REGION : "us-east-1"
    # AWS_ACCOUNT_ID with a value of account-ID
    IMAGE_TAG: "latest" # parameterize this
    IMAGE_REPO_NAME: "react-games"

phases:
  install:
    runtime-versions:
      golang: 1.12
      docker: 18:09.0

  pre_build: 
   commands:
     - echo Logging in to Amazon ECR
     - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
     # Why on earth would this not be the default?
     - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
     - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  build:
    commands:
      # Build our application
      - cd server
      - go build -o server
      # Docker stuff
      - echo Build started on `date`
      - echo Building Docker images...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGETAG $ECRID/$IMAGE_REPO_NAME:$IMAGETAG
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECRID/$IMAGE_REPO_NAME:$IMAGE_TAG

